- name: all in vagrant
  hosts: test_server
  remote_user: vagrant
  tasks:
    #  Эта часть компилирует динамическую библиотеку и устанавливает ее на виртуальную машину
    - name: install dependencies
      become: true
      ansible.builtin.apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - cmake
        - gcc
        - make
        - build-essential
        - unzip
    - name: create work directory
      ansible.builtin.file:
        path: /home/vagrant/sqlite3
        state: directory
        mode: '0755'
    - name: unarchive files with sqlite3 code 
      ansible.builtin.unarchive:
        src: https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip
        dest: /home/vagrant/sqlite3
        remote_src: yes
    - name: create directory for build 
      ansible.builtin.file:
        path: /home/vagrant/sqlite3/build
        state: directory
        mode: '0755'
    - name: copy CMakeLists.txt
      ansible.builtin.copy:
        src: CMakeLists.txt
        dest: /home/vagrant/sqlite3/sqlite-amalgamation-3260000/CMakeLists.txt
        owner: vagrant
        group: vagrant
        mode: '0755'
    - name: create directory for logs 
      become: true
      ansible.builtin.file:
        path: /var/log/sqlite3
        state: directory
        mode: '0755'
    - name: generate Makefile with CMake 
      ansible.builtin.command:
        cmd: cmake /home/vagrant/sqlite3/sqlite-amalgamation-3260000
      args:
        chdir: /home/vagrant/sqlite3/build/
    - name: compilation Makefile with CMake
      become: true
      ansible.builtin.shell: |
        cmake --build . > /var/log/sqlite3/compilation.log 2>&1
      args:
        chdir: /home/vagrant/sqlite3/build/
    - name: install binary code with CMake
      become: yes
      ansible.builtin.command:
        cmd: cmake --install .
      args:
        chdir: /home/vagrant/sqlite3/build/
    
    # Эта часть отвечает за build образа в котором компилируется libsqlite3.so
    - name: copy Dockerfile
      ansible.builtin.copy:
        src: Dockerfile
        dest: /home/vagrant/sqlite3/sqlite-amalgamation-3260000/Dockerfile
        owner: vagrant
        group: vagrant
        mode: '0755'
    - name: build Docker image
      become: yes
      community.docker.docker_image:
        name: sqlite3-local
        build:
          path: /home/vagrant/sqlite3/sqlite-amalgamation-3260000
        state: present
        source: build
    - name: start local docker container 
      become: yes
      community.docker.docker_container:
        name: sqlite3-local
        image: sqlite3-local 
        state: present 

    # Эта часть берет образ Docker с Docker Hub и запускает контейнер (я не до конца понял что именно нужно в задании)
    - name: start docker container from docker hub
      become: yes
      community.docker.docker_container:
        image: bakvivas/build-sqlite3
        name: build-sqlite3
        state: present

    # Удаляю промежуточные файлы для легковесности виртуальной машины
    - name: delete intermediate files
      ansible.builtin.file:
        path: /home/vagrant/sqlite3
        state: absent
