- name: install Docker
  hosts: test_server
  remote_user: vagrant
  become: true
  tasks:
    - name: install dependencies
      ansible.builtin.apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - curl
        - software-properties-common
        - apt-transport-https
        - gnupg-agent
        - ca-certificates
    - name: GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: install docker
      ansible.builtin.apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: check and start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
    - name: adding vagrant user to docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: yes
